Social-Network-master/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Social-Network-master/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

Social-Network-master/profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    profiles_list_view,
    invite_profiles_list_view,
    ProfileDetailView,
    ProfileListView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
    search_profile,

     my_profile_view_edit
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    # these is for the search reasut
    path('search/', search_profile, name="search-profile"),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
      path('myprofile/profile_edite', my_profile_view_edit,
         name='my-profile-view-edit'),
]

Social-Network-master/profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
# Create your models here.

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)
        print("#########")

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)
        print("#########")

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        print("#########")
        return available
        

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="no bio...", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(default='user.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse("profiles:profile-detail-view", kwargs={"slug": self.slug})
    
    def get_friends(self):
        return self.friends.all()

    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked += 1
        return total_liked

    def get_likes_recieved_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked


    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"
        

    
        

Social-Network-master/profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

Social-Network-master/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None,
                            request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    return render(request, 'profiles/myprofile.html', context)


@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {
        'qs': results,
        'is_empty': is_empty,
    }

    return render(request, 'profiles/my_invites.html', context)


@login_required
def accept_invatation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites-view')


@login_required
def reject_invatation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites-view')


@login_required
def invite_profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)
    context = {'qs': qs}
    return render(request, 'profiles/to_invite_list.html', context)


@login_required
def profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)
    context = {'qs': qs}
    return render(request, 'profiles/profile_list.html', context)


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    # def get_object(self):
    #     slug = self.kwargs.get('slug')
    #     profile = Profile.objects.get(slug=slug)
    #     return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(
            self.get_object().get_all_authors_posts()) > 0 else False
        return context


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    # context_object_name = 'qs'

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context


@login_required
def send_invatation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(
            sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')


@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (
                Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

# custom
@login_required
def my_profile_view_edit(request):
    profile = Profile.objects.get(user=request.user)
    # THESE IS FOR THE CHANGE PROFILE
    form = ProfileModelForm(request.POST or None,
                            request.FILES or None, instance=profile)
    # TO  CONFIRM
    confirm = False
    #  TO CHECK WEATHER THE PSOTS IS UPLADED FOR NOT
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
            context = {
                'profile': profile,
                'form': form,
                'confirm': confirm,
            }
            return render(request, 'profiles/myprofile.html', context)
    else:
        context = {
            'profile': profile,
            'form': form,
            'confirm': confirm,
        }
        return render(request, 'profiles/pro_edite.html', context)


def search_profile(request):
    query = request.GET['query']
    if len(query) > 78:
        allProfiles = Profile.objects.none()
    else:
        allname = Profile.objects.filter(first_name__icontains=query)
        alllast_name = Profile.objects.filter(last_name__icontains=query)
        allbio = Profile.objects.filter(bio__icontains=query)
        allProfiles = allname.union(alllast_name, allbio)
    context = {
        'query': query,
        'allProfiles': allProfiles,
    }
    return render(request, 'profiles/search.html', context)



# def handelLogout(request):
#     logout(request)
#     messages.success(request, "Successfully logged out")
#     return redirect('http://127.0.0.1:8000/')

Social-Network-master/profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
profile detail
{% endblock title %}

{% block content %}
<div class="ui grid">
    <br>
    <div class="row">
        <div class="four wide column">
            <img class="ui medium rounded image" src={{object.avatar.url}}>
            <h1>{{object.user}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.get_posts_no }}</div>
                </div>
                <div class="item">
                    Likes given
                    <div class="ui label">{{ object.get_likes_given_no }}</div>
                </div>
                <div class="item">
                    Likes received
                    <div class="ui label">{{ object.get_likes_recieved_no }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.get_friends_no }}</div>
                </div>
            </div>

            {% if object.user not in rel_receiver and object.user not in rel_sender %}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                </form>
            {% endif %}

            {% if object.user in rel_receiver and request.user not in object.friends.all %}
                <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
            {% endif %}

            {% if request.user in object.friends.all %}
                <form action="{% url 'profiles:remove-friend' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{object.pk}}>
                    <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                </form>
            {% endif %}

        </div>
        <div class="twelve wide column">
            {% if len_posts %}
                {% for post in posts %}
                    <div class="segment ui fluid">
                        {{post.content}}
                    </div>
                {% endfor %}
            {% else %}
                <h1>No posts of this user ...</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

Social-Network-master/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}
{% url 'profiles:my-profile-view-edit' as path_to_edit_profile %}
{% block title %}
my profile
{% endblock title %}

{% block content %}

<div class="ui grid inverted container container_desigen_bg">
    {% if confirm %}
    <div class="ui green message">Your profile has been updated</div>
    {% endif %}

    <!-- these is for the user image and for the profile pic -->
    <div class="row" style="
    background-image: url('{{profile.avatar.url}}');
    background-repeat: no-repeat;
    background-position:center;
    background-size: cover;
    color: #000;
    border-radius: 2px;


">
        <div class="five wide column">

        </div>
        <div class="six wide column">
            <div style="text-align: center;">
                <img src="{{profile.avatar.url}}" style="align-content: center;
            height: 13rem;
            width: 13rem;
            border: 7px solid rgba(255, 255, 255, .15);
            border-radius: 50%;
             margin-top:6rem;
        ">
            </div>
        </div>
        <div class="four wide column">
        </div>
    </div>

    <!-- name and otehrs -->
    <div style="height:10rem; " class="">
        <h1 style="text-align: center; text-transform: capitalize;">
            {{profile.first_name}}
            {{profile.last_name}}
        </h1>
        <p style="text-align: center;"> {{profile.bio}}</p>
        <p style="text-align: center;"><a href="/profiles/myprofile/profile_edite"><b>Edite Your Pro</b></a></p>
    </div>




    <!-- these is for navbar -->
    <div style="background: #323232 !important; height:70px; margin: 0px; " class="ui inverted menu nav  ">
        <div class="ui container  ">
            <a href="/posts/" class=" item">
                Posts: {{profile.get_posts_no}}
            </a>
            <a href="/posts/" class=" item">
                NewPosts: {{profile.get_posts_no}}
            </a>
            <a href="/posts/" class=" item">
                Photos: {{profile.get_posts_no}}
            </a>
            <a href="/posts/" class=" item">
                Videos: 0
            </a>
            <a href="/posts/" class=" item">
                Friends: {{profile.get_friends_no}}
            </a>
            <a href="/posts/" class=" item">
                Favourites: {{profile.get_likes_given_no}}
            </a>
            <div class="item float right ">
                <form action="" method="GET">
                    <div class="ui action left icon input">
                        <input class="prompt" type="text" name="q" placeholder="name of a friend...">
                        <i class="search icon"></i>
                        <button type="submit" class="ui button">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- these is for other sections -->
    <div class="row">
        <div class="six wide column ">
            <h1>firends</h1>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta ab eum quas possimus rerum itaque fuga, et
            ipsa nihil labore incidunt asperiores eveniet earum in nostrum doloribus mollitia beatae! Distinctio?
        </div>
        <div class="ten wide column ">
            {% for obj in qs %}
            <div class="ui fluid card">
                <div class="content">
                    <div class="right floated meta">
                        <div class="ui grid">
                            <div class="row">
                                {% ifequal request.user obj.author.user %}
                                <a href="{% url 'posts:post-update' obj.pk %}"><button
                                        class="ui button bwhite-lg ">Update</button></a>
                                <a href="{% url 'posts:post-delete' obj.pk %}"><button
                                        class="ui button bwhite-lg ">Delete</button></a>
                                {% endifequal %}
                            </div>
                        </div>
                    </div>
                    <img class="ui avatar image" src={{obj.author.avatar.url}}>
                    {{ obj.author.user }} - {{ obj.created|timesince}} ago
                </div>
                <div class="ui fluid image">
                    {% if obj.image %}
                    <img src={{obj.image.url}}>
                    {% endif %}
                </div>
                <div class="content">
                    <p> {{ obj.content }} </p>
                    <div class="right floated">
                        <form action="{% url 'posts:like-post-view' %}" method="POST" class='like-form' id='{{obj.id}}'>
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{obj.id}}>

                            <button type="submit" class="ui button like-btn{{obj.id}}">
                                {% if profile not in obj.liked.all %}
                                Like
                                {% else %}
                                Unlike
                                {% endif %}
                            </button>
                            <div class="ui grid">
                                <div class="column">
                                    <div class="like-count{{obj.id}}"> {{obj.num_likes}} </div>
                                </div>
                                <div class="column">
                                    likes
                                </div>
                            </div>
                        </form>
                    </div>
                    <i class="comment icon"></i>
                    <span> {{ obj.num_comments }} comments</span>
                </div>
                <div class="extra content">
                    <!-- {% if num_comments < 0 in obj.comment_set.all %} <p>You! Haven't get andy comment Yet.</p>
                            {% else %}
                            <button style="width:100%;" class="cmt_btn ui button mb-5 w-full ">show / hide comments</button>
                            {% endif %} -->

                    <button style="width:100%;" class="cmt_btn ui button mb-5 w-full ">show / hide comments</button>



                    <div class="comment-box">
                        {% if obj.comment_set.all %}
                        {% for c in obj.comment_set.all %}
                        <div class="ui segment mb-5">
                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                            <span>{{ c.user }}</span>
                            <div class='mt-5'>{{ c.body }}</div>
                        </div>

                        {% endfor %}
                        {% endif %}
                    </div>

                    <form action="" method="POST" class='ui fluid form'>
                        <div class="ui grid">
                            <div class="row">
                                <div class="thirteen wide column">
                                    {% csrf_token %}
                                    <input type="hidden" name="post_id" value={{obj.id}}>
                                    {{ c_form }}
                                </div>
                                <div class="three wide column ">
                                    <button type="submit" name="submit_c_form"
                                        class="ui primary button  w-full">Send</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br><br><br><br>





    <div class="ui segment">
        <!-- <h3>my profile: {{request.user}}</h3> -->
        <div class="ui grid">
            <div class='row'>
                <div class='six wide column'>
                    <!--  <img class="ui medium rounded image" src="{{profile.avatar.url}}">
                <a href="">{{profile.avatar.url}}</a>
                <a href="">{{profile.avatar}}</a>
                <div class="row mt-5"> -->
                    <!-- <button class='ui secondary button' id='modal-btn'>Update your profile</button> -->
                    <!-- <a href="{{path_to_edit_profile}}" class='ui secondary button' id='modal-btn'>Update your
                        profile</a>
                    <a href="/profiles/myprofile/profile_edite" class='ui primary button' id='modal-btn'>Update your
                        profile</a> -->
                    <h1>six</h1>
                </div>

                <div class="ten wide column">
                    <table class="ui table">
                        <tbody>
                            <tr>
                                <td>username</td>
                                <td>{{profile.user}}</td>
                            </tr>
                            <tr>
                                <td>first name</td>
                                <td>{{profile.first_name}}</td>
                            </tr>
                            <tr>
                                <td>last name</td>
                                <td>{{profile.last_name}}</td>
                            </tr>
                            <tr>
                                <td>bio</td>
                                <td>{{profile.bio}}</td>
                            </tr>
                            <tr>
                                <td>number of friends</td>
                                <td>{{profile.get_friends_no}}</td>
                            </tr>
                            <tr>
                                <td>friends:</td>
                                <td>
                                    <ul>
                                        {% for friend in profile.get_friends %}
                                        <li>{{friend}}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                            <tr>
                                <td>number of posts</td>
                                <td>{{profile.get_posts_no}}</td>
                            </tr>
                            <tr>
                                <td>number of likes given</td>
                                <td>
                                    {{profile.get_likes_given_no}}

                                </td>
                            </tr>
                            <tr>
                                <td>number of likes received</td>
                                <td>{{profile.get_likes_recieved_no}}</td>
                            </tr>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>

<style>
    .container_desigen_bg {
        background: #282828;
        /* color: #f3f3f3;*/
        color: #fff;
    }
</style>




{% endblock content %}

Social-Network-master/profiles/templates/profiles/search.html
{% extends 'base.html' %}
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% block title %}
Searching for: {{query}}
{% endblock title %}

{% block content %}
<div class="ui container">
      <h3>Search results for : <i><a href="/profiles/search/?query={{query}}">{{query}}</a></i></h3>
      {% if allProfiles|length < 1 %} <h2>No search results</h2>

            <h2>Your search query : <b>{{query}}</b> did not match any documents. <br>
                  Suggestions:</h2>
            <h3>
                  <ul>
                        <li>Make sure that all words are spelled correctly.</li>
                        <li>Try more general keywords.</li>
                        <li> Try fewer keywords.</li>
                        <li> Try different keywords.</li>
                        </li>
                  </ul>

            </h3>
            {% endif %}
            {% for user in allProfiles %}
            <div class="ui segment">
                  <div class="ui grid">
                        <div class="row">
                              <div class="three wide column">
                                    <img class="ui small circular image" src={{user.avatar.url}}>
                              </div>
                              <div class="thirteen wide column">
                                    <h3>{{user.user}} {{user.last_name}}</h3>
                                    <p>{{user.bio}}</h3>
                                          <br>
                                          <a href="">
                                                <button class="ui primary button w-big mb-5">See profile</button>
                                          </a>
                                    <form action="{% url 'profiles:accept-invite' %}" method="POST">
                                          {% csrf_token %}
                                          <input type="hidden" name="profile_pk" value={{user.pk}}>
                                          <button type="submit" class="ui positive basic button w-big mb-5">
                                                <i class="check icon"></i>
                                                Accept invite
                                          </button>
                                    </form>
                                    <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                          {% csrf_token %}
                                          <input type="hidden" name="profile_pk" value={{user.pk}}>
                                          <button type="submit" class="ui negative basic button w-big mb-5">
                                                <i class="close icon"></i>
                                                Reject invite
                                          </button>
                                    </form>
                              </div>
                        </div>
                  </div>
            </div>
            {% endfor %}

</div>
{% endblock content %}