Social-Network-master/bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Social-Network-master/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

Social-Network-master/profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    invites_received_view,
    profiles_list_view,
    invite_profiles_list_view,
    ProfileDetailView,
    ProfileListView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
    search_profile,

     my_profile_view_edit
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    # these is for the search reasut
    path('search/', search_profile, name="search-profile"),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
      path('myprofile/profile_edite', my_profile_view_edit,
         name='my-profile-view-edit'),
]

Social-Network-master/templates/main/footer.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<!-- ************************************  fotter *********************************************** -->
<div class="ui invertrd" style=" border-radius: 0px !important;
    padding: 10px 0 10px 0 !important;
    background-color: #323232 !important;
    margin-top:20px;
    " class="container-fluid text-center">
    <footer class="bgcoool invertrd">
        <div class="row">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-center">© 2021 {{localtime}}</small>
                <small class="d-block mb-3 text-center">bffbooks.Com</small>
            </div>
    </footer>
</div>
<style>
    .bgcoool {
        height: 60px;
    }

    .text-center {
        display: flex;
        justify-content: center;
        text-align: center;
        color: beige;
        font-size: large;
    }
</style>
<!-- ************************************ end of  fotter *********************************************** -->

Social-Network-master/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}


<div class="ui grid container">
    <br>

    <hr>
    <div class="ui row">
        <div class="column six wide">
            <h1>Bffbook</h1>
            <p class="description">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque, repellat deleniti! Temporibus eum
                nostrum assumenda. Quasi architecto facere cupiditate dolorem non voluptatem quam dolore voluptate
                laudantium? Voluptates quo ab ratione?
            </p>
        </div>
        <div class="column eight wide">
            <div class="ui form">
                <form action="/login" method="POST">
                    <div class="field">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" id="loginusername" name="loginusername"
                            placeholder="Enter your username " required>
                    </div>
                    <div class="field">
                        <label for="pass">Enter your password </label>
                        <input type="password" class="form-control" id="loginpassword" name="loginpassword"
                            placeholder="Enter your password " required>
                    </div>
                    {% csrf_token %}
                    <button type="submit" class="ui green tiny button">login</button>
                </form>
            </div>
        </div>
        <div class="column one wide">
            <a href="/singup_page">
                <div class="ui blue small button">
                    SignUp
                </div>
            </a>
        </div>
    </div>
</div>

<hr>
<div class="ui container">
    <h1>These is the lorem!</h1>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. At harum, odio natus tenetur explicabo facere vero
        molestiae recusandae rem. Eligendi laboriosam esse maxime laborum? Nobis cumque eaque neque quo ea. Non possimus
        dolores corporis aliquid enim accusamus architecto ratione libero, molestiae cumque fuga. Animi nam quibusdam,
        excepturi quasi aliquid, eaque voluptatum dolore, alias repudiandae itaque inventore facilis a. Praesentium
        eligendi
        vitae, nihil magnam nesciunt architecto aliquam consequatur perferendis sit, nulla, molestias optio ex! Quaerat,
        esse quo at suscipit consectetur sunt distinctio eos ratione veritatis, repellendus mollitia possimus rem
        aperiam
        dolore, necessitatibus quasi eaque minus. Pariatur minus possimus reiciendis debitis ipsum?
    </p>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. At harum, odio natus tenetur explicabo facere vero
        molestiae recusandae rem. Eligendi laboriosam esse maxime laborum? Nobis cumque eaque neque quo ea. Non possimus
        dolores corporis aliquid enim accusamus architecto ratione libero, molestiae cumque fuga. Animi nam quibusdam,
        excepturi quasi aliquid, eaque voluptatum dolore, alias repudiandae itaque inventore facilis a. Praesentium
        eligendi
        vitae, nihil magnam nesciunt architecto aliquam consequatur perferendis sit, nulla, molestias optio ex! Quaerat,
        esse quo at suscipit consectetur sunt distinctio eos ratione veritatis, repellendus mollitia possimus rem
        aperiam
        dolore, necessitatibus quasi eaque minus. Pariatur minus possimus reiciendis debitis ipsum?
    </p>


    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. At harum, odio natus tenetur explicabo facere vero
        molestiae recusandae rem. Eligendi laboriosam esse maxime laborum? Nobis cumque eaque neque quo ea. Non possimus
        dolores corporis aliquid enim accusamus architecto ratione libero, molestiae cumque fuga. Animi nam quibusdam,
        excepturi quasi aliquid, eaque voluptatum dolore, alias repudiandae itaque inventore facilis a. Praesentium
        eligendi
        vitae, nihil magnam nesciunt architecto aliquam consequatur perferendis sit, nulla, molestias optio ex! Quaerat,
        esse quo at suscipit consectetur sunt distinctio eos ratione veritatis, repellendus mollitia possimus rem
        aperiam
        dolore, necessitatibus quasi eaque minus. Pariatur minus possimus reiciendis debitis ipsum?
    </p>
</div>

{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function () {
        console.log('working')
    })
</script>
{% endblock scripts %}

Social-Network-master/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<div class="ui inverted top fixed menu mb-7">
    <div class="ui container">
        <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
            <h3>bffbook</h3>
        </a>
        {% if request.user.is_authenticated %}
        <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
            Board
        </a>
        {% endif %}

        <div class="right menu">
            {% if request.user.is_authenticated %}

            <a href="{{path_to_all_profiles}}"
                class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                All Profiles
            </a>


            <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                Send Invites
            </a>


            <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
            </a>

            <div class="item">
                <form action="/profiles/search/" method="GET" id="query">
                    <div class="ui action left icon input">
                        <input class="prompt" type="text" name='query' placeholder="name of a friend...">
                        <i class="search icon"></i>
                        <button type='submit' class="ui button">Search</button>
                    </div>
                </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
            {% else %}
            <a href="" class="ui item">
                Login
            </a>
            {% endif %}
        </div>
    </div>
</div>